### ISSUE TITLE
Doesn't upload products

### ISSUE THREAD

**Issue by Amedari4** [franko20/Agroculture-#1]
Farmers can't upload products. it says product uploaded successfully but doesn't reflect on product menu or on database.

**Comment by franko20** [comment]
did you imported the sql file properly?

**Comment by franko20** [comment]
> Farmers can't upload products. it says product uploaded successfully but doesn't reflect on product menu or on database.

use xampp server or wamp server to import the sql file.

**Comment by franko20** [comment]
Also I added new file : _error.php_
